### ISSUE TITLE
AMQP channels question

### ISSUE THREAD

**Issue by janajri** [dropbox/amqp-coffee#40]
We've recently gone live to production using your library to bridge RabbitMQ queues with clients who go on/off line quite frequently (think mobile). Whenever a client comes online we send a consume to the rabbitmq server and then when the client goes offline, we fire a consume.close(). During our beta stage things seemed to have gone just fine, however, recently, we've been seeing many open channels on our rabbitmq server that have no consumers. I was under the impression that a single channel would suffice for consuming for multiple queues where each queue ties to one client and one client only. Is my mental model incorrect?

Any thoughts?
Code looks somehting like this:

```javascript
  var Conn = Rabbit.get();
   client.consumer = Conn.consume(/* params*/);
   ...
   client.on('disconnected', function(){
     client.consumer.close();
   });
```

**Comment by barshow** [comment]
It is possible to use the same channel for multiple consumers, however thats not how its implemented in amqp-coffee due to the way we abstract qos and message confirms.  But your mental model could be correct.  

Your code snippet is also correct, however a consumer may fail for other reasons, like a reconnect and the queues gone or something of that sort.  Anything unique about the queues you are using.  Are they setup and deleted often? Auto delete? exclusive?  After i know that I can try and make a test to figure out whats going on.  You can also turn debugging on and see whats actually happening with the channel numbers that are still open.  `DEBUG=amqp* AMQP=3` is usually a good level to start.

I am not sure what the generally desired behavior of consumers is here with regards to individual channels or shared.  But at the very least there should be an option for sharing channels.  Its a bit complicated especially with confirms so ill work on that.

**Comment by janajri** [comment]
@barshow thanks for the quick response. The queues are always persisted, if a 404 returns from a consume, we declare the queue before resending a consume command. Here is some more code to show how we implement your lib. Also, you'll see that we call consume for each new client session which is what we are ok with for now since the limit is 65k. We don't need anything close to that for now, so one channel per client is fine for now. What we are seeing is our node procs balloon in memory. Now, the leak may not be happening here or even in your library but our recent move to use rabbitmq on our front-end fleet has resulted in this which is why I'm investigating: 

![screen shot 2015-07-24 at 7 50 44 pm](https://cloud.githubusercontent.com/assets/2857405/8886722/5150b34a-323d-11e5-8d1a-5654f2dca956.png)
 fyi, that's a one hour interval

Here is some more context regarding our implementation. I'll try to observer the debug logs.

```javascript
Session.prototype.subscribe = function(listener, done) {
  var self = this;
  var prefetch = {
    prefetchCount: 20
  }
  var opts = xtend({
    queue: self.name
  }, defaultOpts);
  Rabbit.queue(opts, function(err, q) {
    if (err) return done(err);
    self.Context = q;
    self.bind(function(err) {
      if (err) return done(err);
      self.Context.messageCount(function(err, count) {
        debug('message count', count);
        self.remoteCount = count || 0;
        self._consumer = Rabbit.consume(self.name, prefetch, listener, done);
        self._consumer.on('error', Email.error)
      })
    })
  })
}

Session.prototype.unsubscribe = function(done) {
  done = done || function() {}
  if (!this._consumer) return done();
  this._consumer.close(done);
}
```

**Comment by barshow** [comment]
I suspect your doing the actual q.declare in self.bind?  You can grab the messageCount from the declare response.

How many channels are getting left open?

It would be helpful for the channel issue for you to run with the debug flags.  we could probably trace down the error in that case

**Comment by janajri** [comment]
@barshow apologies for leaving this open, still investigating this issue. Will re-open if I find any more info on this matter from our end. Thank you again, this module has certainly empowered us to move a bit faster in integration RabbitMQ on our end.

**Comment by barshow** [comment]
@janajri please do Im always looking to improve this!  Let me know if anything comes up.
